### ISSUE TITLE
"In file(file, "rt") :   cannot open file 'KH2012_KY2019.txt': No such file or directory"

### ISSUE THREAD

**Issue by prakritipaul** [kewiechecki/CrobustaTFs#1]
Hi! 
I am trying to download your package- I cloned your git repository, entered the "CrobustaTFs" directory and tried the make command. However, I ran into the issue in the header. Below was my console output.

Rscript --vanilla data-raw/getOrthologs.R
Rscript --vanilla data-raw/DATASET.R
Loading required package: TFBSTools

Error in file(file, "rt") : cannot open the connection
Calls: mergeMotifs -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'KH2012_KY2019.txt': No such file or directory
Execution halted
make: *** [data] Error 1

I was hoping you could place the missing text file in the repo. I suspect that you may also have the same issue in your "CrobustaDA: Differential accessibility pipeline for Ciona robusta." package. 

Many thanks!
prakritipaul

**Comment by kewiechecki** [comment]
I added the missing file to the repo. The make command should work now.

**Comment by prakritipaul** [comment]
Thanks!
